#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# g-e-o-m-e-t-r-i-c's ~/.SpaceVim.d/init.toml - configuration for SpaceVim.
# Directory: ~/.SpaceVim.d

[options]

# Indentation options: use 4 spaces and tabs
default_indent = 4
expand_tab = false

# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme layer
colorscheme = "NeoSolarized"
colorscheme_bg = "dark"

# Disable guicolors in basic mode, many terminal do not support 24bit true colors
enable_guicolors = true

# Disable statusline separator, if you want to use other value, please install nerd fonts
statusline_separator = "arrow"
statusline_iseparator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = false

updatetime = 500

# use a better filetree
filemanager = "vimfiler"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'colorscheme'  # gives me access to other colorschemes, apart from gruvbox

# git
[[layers]]
name = 'git'

# allows me to view diffs in the statusline, among other things
[[layers]]
name = 'VersionControl'

[[layers]]
name = 'incsearch'

[[custom_plugins]]
# custom theme
repo = "sainnhe/gruvbox-material"

# some git integration plugins
# [[custom_plugins]]
# repo = "tpope/vim-fugitive"  # causes problems with dein, so use at your own risk!

[[custom_plugins]]
repo = "Xuyuanp/nerdtree-git-plugin"

# better syntax
[[custom_plugins]]
repo = "sheerun/vim-polyglot"

# LaTeX
[[custom_plugins]]
repo = "vim-latex/vim-latex"

[[custom_plugins]]
repo = "lervag/vimtex"
