# g-e-o-m-e-t-r-i-c's ~/.config/starship.toml - config file for Starship
# Directory: ~/.config/

# NOTE: Fonts without proper icon support might fail to work. Please use a Nerd Font or a patched font of your own.

# Don't print a newline before the prompt.
add_newline = false
command_timeout = 1000

# Don't print a newline before the prompt symbol
[line_break]
	disabled = true

# Git Configurations
[git_commit]
	commit_hash_length = 5

# Shows the number of lines added, changed, or deleted.
[git_metrics]
	disabled = false

# Shows the number of files changed, number of files deleted etc.
[git_status]
	conflicted = "=${count}"
	ahead = "⇡${count}"
	behind = "⇣${count}"
	diverged = "⇕ ⇡${ahead_count}⇣${behind_count}"
	untracked = "?"
	stashed = "$${count}"
	modified = "!${count}"
	staged = "+${count}"
	renamed = "»${count}"
	deleted = "✘${count}"
	style = "bold blue"

# Nerd Font Icons: Only enable if you have a Nerd Font or your own patched font.
# [aws]
#     symbol = "  "
#
# [conda]
#     symbol = " "
#
# [dart]
#     symbol = " "
#
# [directory]
#     read_only = " "
#
# [docker_context]
#     symbol = " "
#
# [elixir]
#     symbol = " "
#
# [elm]
#     symbol = " "
#
# [git_branch]
#     symbol = " "
#
# [golang]
#     symbol = " "
#
# [hg_branch]
#     symbol = " "
#
# [java]
#     symbol = " "
#     style = "red"
#
# [julia]
#     symbol = " "
#
# [lua]
#     symbol = " "
#
# [memory_usage]
#     symbol = " "
#
# [nim]
#     symbol = " "
#
# [nix_shell]
#     symbol = " "
#
# [package]
#     symbol = " "
#
# [perl]
#     symbol = " "
#
# [php]
#     symbol = " "
#
# [python]
#     symbol = " "
#
# [ruby]
#     symbol = " "
#
# [rust]
#     symbol = " "
#
# [scala]
#     symbol = " "
#
# [shlvl]
#     symbol = " "
#
# [swift]
#     symbol = "ﯣ "
